name: Java app CI/CD

run-name: ${{ github.actor }} is building java applications

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build_package:
    runs-on: ubuntu-22.04

    steps:
    - name: checkout Git repository
      uses: actions/checkout@v4

    - name: select specific java package
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: check version java and maven
      run: |
        java -version 
        mvn --version

    - name: build java package
      run: mvn clean package

    - name: check artifact
      run: ls -la  ${{ github.workspace }}/target
